version: '3'

services:

  djangoapp:
    build: .
    restart: always
    env_file:
      - configs/app/env
    volumes:
      - .:/code
    command: gunicorn -b 0.0.0.0 -p 8000 backend.wsgi
    networks:
      - nginx_network
      - database_network
    depends_on:
      - database

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - configs/app/env
    volumes:
      - ./configs/nginx:/etc/nginx/conf.d
      - ./static_files:/code/static_files
      - ./media:/code/media
      - ./frontend:/code/frontend
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - nginx_network
    depends_on:
      - djangoapp

  database:
    image: postgres:11
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - configs/app/env
    volumes:
      - /var/lib/postgresql/data
      - ./configs:/code
    networks:
      - database_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  database_volume:
