# Generated by Django 2.2b1 on 2020-03-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('apikey', models.CharField(max_length=255, verbose_name='api key')),
            ],
            options={
                'verbose_name': 'Настройки конференций',
                'verbose_name_plural': 'Настройки конференций',
            },
        ),
    ]
