# Generated by Django 2.2b1 on 2019-04-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190424_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
    ]
