# Generated by Django 2.2b1 on 2019-04-24 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_question_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баллы за ответ'),
        ),
    ]
