# Generated by Django 2.2b1 on 2019-04-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_answer_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='score',
        ),
    ]
