# Generated by Django 2.2b1 on 2019-04-25 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_remove_answer_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPassing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('status', models.SmallIntegerField(choices=[(0, 'Не начато'), (1, 'Начато'), (2, 'Пройдено')], default=0, verbose_name='Статус прохождения')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_passings', to='courses.Material', verbose_name='Материал')),
                ('user', models.ForeignKey(limit_choices_to={'user_status': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='material_passings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прохождение материала',
                'verbose_name_plural': 'Прохождение материалов',
                'ordering': ['-created'],
            },
        ),
    ]
