# Generated by Django 2.2b1 on 2019-05-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190426_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passing',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='passing',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время начала'),
        ),
    ]
