# Generated by Django 2.2b1 on 2019-05-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190514_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passing',
            name='success_passed',
        ),
    ]
