# Generated by Django 2.2b1 on 2019-05-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_passing_success_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='passing',
            name='success_passed',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Успешно'), (1, 'Не пройдено'), (2, 'На проверке')], default=1, verbose_name='Статус прохождения'),
        ),
    ]
