# Generated by Django 2.2b1 on 2019-05-24 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_bookmark_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='retake_time',
        ),
        migrations.AddField(
            model_name='task',
            name='retake_hours',
            field=models.SmallIntegerField(default=36, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во часов для интервала пересдачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attempts',
            field=models.SmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во попыток'),
        ),
        migrations.AlterField(
            model_name='task',
            name='passing',
            field=models.SmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Процент ответов для прохождения'),
        ),
    ]
