# Generated by Django 2.2b1 on 2019-06-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190524_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='passing',
            name='out_of_time',
            field=models.BooleanField(default=False, verbose_name='Разрешить пересдачу без интервала'),
        ),
    ]
