# Generated by Django 2.2b1 on 2019-06-17 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_passing_out_of_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальные баллы за ответ'),
        ),
    ]
