# Generated by Django 2.2b1 on 2019-06-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20190617_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='passing',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Результат проверки'),
        ),
    ]
