# Generated by Django 2.2b1 on 2019-06-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_passing_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['rank', 'title', '-created'], 'verbose_name': 'Материалы курса', 'verbose_name_plural': 'Материалы курсов'},
        ),
        migrations.AddField(
            model_name='material',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Очереднось показа'),
        ),
    ]
