# Generated by Django 2.2b1 on 2019-07-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20190624_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.TextField(blank=True, null=True, verbose_name='Текстовое представление преподавателя'),
        ),
    ]
