# Generated by Django 2.2b1 on 2019-09-25 10:51

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20190920_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.Material', verbose_name='Родительский материал'),
        ),
        migrations.AlterField(
            model_name='passing',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_passings', to='courses.Task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.Material', verbose_name='Материал'),
        ),
    ]
