# Generated by Django 2.2b1 on 2019-09-25 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0021_auto_20190925_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderator_courses', to=settings.AUTH_USER_MODEL, verbose_name='Модераторы курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор курса'),
        ),
    ]
