# Generated by Django 2.2b1 on 2019-10-15 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20190925_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='original_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Название материала'),
        ),
    ]
