# Generated by Django 2.2b1 on 2019-11-27 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_material_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='level',
        ),
        migrations.RemoveField(
            model_name='material',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='material',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='material',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='material',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.Material', verbose_name='Родительский материал'),
        ),
    ]
