# Generated by Django 2.2b1 on 2019-11-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20191127_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='retake_hours',
        ),
        migrations.AddField(
            model_name='task',
            name='retake_seconds',
            field=models.PositiveIntegerField(default='0', verbose_name='Интервала пересдачи'),
        ),
    ]
