# Generated by Django 2.2b1 on 2019-12-03 07:01

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20191127_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='course_pdf/', validators=[upload_validator.FileTypeValidator(allowed_extensions=['.pdf'], allowed_types=['application/pdf'])], verbose_name='PDF контент'),
        ),
        migrations.AlterField(
            model_name='material',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='course_video/', verbose_name='Видео контент'),
        ),
    ]
