# Generated by Django 2.2b1 on 2020-01-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20191222_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='text_explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Описание с хэштегами'),
        ),
    ]
