# Generated by Django 2.2b1 on 2020-02-10 09:14

import backend.utils.methods
from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_task_text_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='pdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=backend.utils.methods.path_and_rename, validators=[upload_validator.FileTypeValidator(allowed_extensions=['.pdf'], allowed_types=['application/pdf'])], verbose_name='PDF контент'),
        ),
        migrations.AlterField(
            model_name='material',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=backend.utils.methods.path_and_rename, verbose_name='Видео контент'),
        ),
    ]
