# Generated by Django 2.2b1 on 2020-02-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_passing_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
