# Generated by Django 2.2b1 on 2020-03-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_task_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passing',
            name='success_passed',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Тест пройден успешно'), (1, 'На проверке'), (2, 'Превышено допустимое время прохождения'), (3, 'Превышено допустимое кол-во попыток'), (4, 'Процент прохождения не набран'), (5, 'Не закончен')], default=5, verbose_name='Статус прохождения'),
        ),
    ]
