# Generated by Django 2.2b1 on 2020-03-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_auto_20200311_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='trial_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во пробных попыток'),
        ),
    ]
