# Generated by Django 2.2.16 on 2020-10-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_task_trial_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='passing',
            name='max_points',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Максимально возможные баллы за тест'),
        ),
        migrations.AddField(
            model_name='passing',
            name='user_points',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Баллы за прохождение теста'),
        ),
    ]
