# Generated by Django 2.2.16 on 2021-03-19 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_auto_20201024_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='trial_percents',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Процент пробных попыток'),
        ),
    ]
