# Generated by Django 2.2.16 on 2021-05-09 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0041_task_trial_percents'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('issued_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Время выдачи')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_issued', to='courses.Task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task_issued', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
