# Generated by Django 2.2.16 on 2021-05-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_issuedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_attempts_to_pass',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Максимальное кол-во сдач'),
        ),
    ]
