# Generated by Django 2.2.16 on 2021-05-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_task_max_attempts_to_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_course',
            field=models.DateField(blank=True, null=True, verbose_name='Время окончания курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='g_chat',
            field=models.BooleanField(default=True, verbose_name='Чат с тех. поддержкой'),
        ),
        migrations.AddField(
            model_name='course',
            name='s_chat',
            field=models.BooleanField(default=False, verbose_name='Чат с одногрупниками'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_course',
            field=models.DateField(blank=True, null=True, verbose_name='Время начала курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='t_chat',
            field=models.BooleanField(default=False, verbose_name='Чат с преподавателем'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
