# Generated by Django 2.2.16 on 2021-06-07 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0044_auto_20210518_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('start_course', models.DateTimeField(verbose_name='Время начала')),
                ('end_course', models.DateTimeField(verbose_name='Время окончания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_user_settings', to='courses.Course', verbose_name='Курсы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'User Course Settings',
                'verbose_name_plural': 'User Course Settings',
                'db_table': 'user_course_setting',
                'ordering': ['-created'],
            },
        ),
    ]
