# Generated by Django 2.2.16 on 2021-06-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_usercoursesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursesettings',
            name='end_course',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
    ]
