# Generated by Django 2.2b1 on 2019-04-24 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0001_initial'),
        ('courses', '0002_auto_20190424_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answers', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий'),
        ),
        migrations.AddField(
            model_name='attempts',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.Course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='attempts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
