# Generated by Django 2.2b1 on 2019-05-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20190424_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='courses.Answer', verbose_name='Выбранный ответ'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ в произвольной форме'),
        ),
    ]
