# Generated by Django 2.2b1 on 2019-06-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_auto_20190522_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user_answer/', verbose_name='Файл пользователя'),
        ),
    ]
