# Generated by Django 2.2b1 on 2019-06-17 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_useranswer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='score',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баллы за ответ'),
        ),
    ]
