# Generated by Django 2.2b1 on 2019-06-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_add_score_to_user_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='score',
            new_name='users_points',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='is_true',
        ),
    ]
