# Generated by Django 2.2b1 on 2019-06-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_auto_20190617_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='users_points',
            new_name='user_points',
        ),
    ]
