# Generated by Django 2.2b1 on 2019-08-17 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_auto_20190817_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user_points',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баллы за ответ'),
        ),
    ]
