# Generated by Django 2.2b1 on 2020-10-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_task_trial_attempts'),
        ('testing', '0013_auto_20200219_0918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('passing', 'question')},
        ),
    ]
