# Generated by Django 2.2b1 on 2020-10-07 12:19

from django.db import migrations


def fill_answers(apps, schema_editor):
    """
    Заполнение нового поля answers из старого answer
    """
    UserAnswer = apps.get_model('testing', 'UserAnswer')
    for item in UserAnswer.objects.all():
        if item.answer:
            item.answers.add(item.answer)


class Migration(migrations.Migration):
    dependencies = [
        ('testing', '0016_auto_20201007_1518'),
    ]

    operations = [
        migrations.RunPython(fill_answers),
    ]
