# Generated by Django 2.2b1 on 2020-10-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0017_auto_20201007_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='u_answers', to='courses.Answer', verbose_name='Выбранные ответы'),
        ),
    ]
