# Generated by Django 2.2b1 on 2020-01-18 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', validators=[django.core.validators.MaxLengthValidator(1048576)], verbose_name='Изображение'),
        ),
    ]
