# Generated by Django 2.2b1 on 2020-01-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0005_auto_20200118_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mess',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
