# Generated by Django 2.2b1 on 2020-03-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0006_auto_20200119_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('apikey', models.CharField(max_length=255, verbose_name='api key')),
            ],
            options={
                'verbose_name': 'Настройки хранилища чатов',
                'verbose_name_plural': 'Настройки хранилища чатов',
            },
        ),
    ]
