# Generated by Django 2.2b1 on 2020-06-07 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mess', '0007_firebasesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочтено')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='mess.Message', verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Сообщение пользователю',
                'verbose_name_plural': 'Сообщения пользователей',
                'unique_together': {('user', 'message')},
            },
        ),
    ]
