# Generated by Django 2.2.16 on 2022-09-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0009_remove_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='author',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
    ]
