# Generated by Django 2.2.16 on 2022-09-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0012_usermessage_chat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='message_text',
            field=models.TextField(default=''),
        ),
    ]
