# Generated by Django 2.2b1 on 2019-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190603_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='end_course',
            field=models.DateField(blank=True, null=True, verbose_name='Время окончания курса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_course',
            field=models.DateField(blank=True, null=True, verbose_name='Время начала курса'),
        ),
    ]
