# Generated by Django 2.2b1 on 2019-06-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useractivity_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='url',
        ),
    ]
