# Generated by Django 2.2b1 on 2019-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_useractivity_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('payload_1', models.TextField(blank=True, null=True, verbose_name='payload 1')),
                ('payload_2', models.TextField(blank=True, null=True, verbose_name='payload 2')),
                ('payload_3', models.TextField(blank=True, null=True, verbose_name='payload 3')),
                ('payload_4', models.TextField(blank=True, null=True, verbose_name='payload 4')),
            ],
            options={
                'verbose_name': 'debug data',
                'verbose_name_plural': 'debug datas',
            },
        ),
    ]
