# Generated by Django 2.2b1 on 2019-06-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_debugmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debugmodel',
            name='payload_3',
        ),
        migrations.RemoveField(
            model_name='debugmodel',
            name='payload_4',
        ),
    ]
