# Generated by Django 2.2b1 on 2019-07-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190609_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curator_company',
            field=models.ManyToManyField(blank=True, related_name='curator_company', to='users.Company', verbose_name='Курируемые компании'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.SmallIntegerField(choices=[(0, 'Администратор'), (1, 'Модератор'), (2, 'Клиент'), (3, 'Куратор')], default=2, verbose_name='Статус пользователя'),
        ),
    ]
