# Generated by Django 2.2b1 on 2019-08-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пароль клиента'),
        ),
    ]
