# Generated by Django 2.2b1 on 2019-08-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190814_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='headers',
            field=models.TextField(blank=True, verbose_name='headers'),
        ),
    ]
