# Generated by Django 2.2b1 on 2019-08-14 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190814_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDayActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('day', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('seconds', models.PositiveSmallIntegerField(default=0, verbose_name='Секунды')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_activity', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Время активности пользователей по дням',
                'verbose_name_plural': 'Время активности пользователей по дням',
                'unique_together': {('user', 'day')},
            },
        ),
    ]
