# Generated by Django 2.2b1 on 2019-08-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userdayactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DebugModel',
        ),
    ]
