# Generated by Django 2.2b1 on 2019-09-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdayactivity',
            name='course_id',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ID курса в момент посещения'),
        ),
    ]
