# Generated by Django 2.2b1 on 2020-10-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200317_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='design',
            field=models.SmallIntegerField(choices=[(0, 'Дефолтный дизайн'), (1, 'Интеллека дизайн')], default=0, verbose_name='Дизайн интерфейса'),
        ),
    ]
