# Generated by Django 2.2.16 on 2021-03-23 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_last_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnlineHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Дата')),
                ('active_clients_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во активных клиентов')),
            ],
            options={
                'verbose_name': 'История активных клиентов',
                'verbose_name_plural': 'История активных клиентов',
            },
        ),
    ]
