# Generated by Django 2.2.16 on 2021-05-09 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_useronlinehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useronlinehistory',
            options={'ordering': ['date'], 'verbose_name': 'История активных клиентов', 'verbose_name_plural': 'История активных клиентов'},
        ),
    ]
