# Generated by Django 2.2.16 on 2021-05-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210509_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEnterStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('payload', models.TextField(blank=True, null=True, verbose_name='payload')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='useractivity',
            name='course_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID курса в момент посещения'),
        ),
    ]
