# Generated by Django 2.2.16 on 2022-06-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210519_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webinars',
            field=models.BooleanField(default=False, verbose_name='Доступность вебинаров'),
        ),
    ]
