# Generated by Django 2.2.16 on 2022-09-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_login', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('curator_login', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('moderator_login', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('admin_login', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('client_password', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('curator_password', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('moderator_password', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('admin_password', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
